[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "https://release.antfu.me/*"
to = "https://releases.antfu.me/:splat"
status = 302
